// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package randomuserapi.proxies;

public class Name
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nameMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RandomUserAPI.Name";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		First("First"),
		Last("Last"),
		Name_JsonObject("RandomUserAPI.Name_JsonObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RandomUserAPI.Name"));
	}

	protected Name(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nameMendixObject)
	{
		if (nameMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RandomUserAPI.Name", nameMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RandomUserAPI.Name");

		this.nameMendixObject = nameMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Name.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static randomuserapi.proxies.Name initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return randomuserapi.proxies.Name.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static randomuserapi.proxies.Name initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new randomuserapi.proxies.Name(context, mendixObject);
	}

	public static randomuserapi.proxies.Name load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return randomuserapi.proxies.Name.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of First
	 */
	public final java.lang.String getFirst()
	{
		return getFirst(getContext());
	}

	/**
	 * @param context
	 * @return value of First
	 */
	public final java.lang.String getFirst(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.First.toString());
	}

	/**
	 * Set value of First
	 * @param first
	 */
	public final void setFirst(java.lang.String first)
	{
		setFirst(getContext(), first);
	}

	/**
	 * Set value of First
	 * @param context
	 * @param first
	 */
	public final void setFirst(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String first)
	{
		getMendixObject().setValue(context, MemberNames.First.toString(), first);
	}

	/**
	 * @return value of Last
	 */
	public final java.lang.String getLast()
	{
		return getLast(getContext());
	}

	/**
	 * @param context
	 * @return value of Last
	 */
	public final java.lang.String getLast(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Last.toString());
	}

	/**
	 * Set value of Last
	 * @param last
	 */
	public final void setLast(java.lang.String last)
	{
		setLast(getContext(), last);
	}

	/**
	 * Set value of Last
	 * @param context
	 * @param last
	 */
	public final void setLast(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String last)
	{
		getMendixObject().setValue(context, MemberNames.Last.toString(), last);
	}

	/**
	 * @return value of Name_JsonObject
	 */
	public final randomuserapi.proxies.User getName_JsonObject() throws com.mendix.core.CoreException
	{
		return getName_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Name_JsonObject
	 */
	public final randomuserapi.proxies.User getName_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		randomuserapi.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Name_JsonObject.toString());
		if (identifier != null)
			result = randomuserapi.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Name_JsonObject
	 * @param name_jsonobject
	 */
	public final void setName_JsonObject(randomuserapi.proxies.User name_jsonobject)
	{
		setName_JsonObject(getContext(), name_jsonobject);
	}

	/**
	 * Set value of Name_JsonObject
	 * @param context
	 * @param name_jsonobject
	 */
	public final void setName_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, randomuserapi.proxies.User name_jsonobject)
	{
		if (name_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Name_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Name_JsonObject.toString(), name_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nameMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final randomuserapi.proxies.Name that = (randomuserapi.proxies.Name) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RandomUserAPI.Name";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
