// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TestSuite module
	public static java.lang.String dS_GetRequiredPage(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			return (java.lang.String)Core.execute(context, "TestSuite.DS_GetRequiredPage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static testsuite.proxies.Color dSO_Color(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TestSuite.DSO_Color", params);
			return result == null ? null : testsuite.proxies.Color.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static testsuite.proxies.Color getUsers(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "TestSuite.GetUsers", params);
			return result == null ? null : testsuite.proxies.Color.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_FlipPrimary(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			Core.execute(context, "TestSuite.IVK_FlipPrimary", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Refresh(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			Core.execute(context, "TestSuite.IVK_Refresh", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SetTekst(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			Core.execute(context, "TestSuite.IVK_SetTekst", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ShowValidations(IContext context, testsuite.proxies.Color _employee)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Employee", _employee == null ? null : _employee.getMendixObject());
			Core.execute(context, "TestSuite.IVK_ShowValidations", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static testsuite.proxies.Color loadData1(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "TestSuite.LoadData1", params);
			return result == null ? null : testsuite.proxies.Color.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static testsuite.proxies.Color loadData3(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "TestSuite.LoadData3", params);
			return result == null ? null : testsuite.proxies.Color.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static testsuite.proxies.Color loadData4(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "TestSuite.LoadData4", params);
			return result == null ? null : testsuite.proxies.Color.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCH_Color(IContext context, testsuite.proxies.Color _color)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Color", _color == null ? null : _color.getMendixObject());
			Core.execute(context, "TestSuite.OCH_Color", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}