// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package randomuserapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the RandomUserAPI module
	public static java.util.List<randomuserapi.proxies.User> get10RandomUsers(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "RandomUserAPI.Get10RandomUsers", params);
			java.util.List<randomuserapi.proxies.User> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<randomuserapi.proxies.User>();
				for (IMendixObject obj : objs)
					result.add(randomuserapi.proxies.User.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<randomuserapi.proxies.User> get15RandomFemaleUsers(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "RandomUserAPI.Get15RandomFemaleUsers", params);
			java.util.List<randomuserapi.proxies.User> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<randomuserapi.proxies.User>();
				for (IMendixObject obj : objs)
					result.add(randomuserapi.proxies.User.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<randomuserapi.proxies.User> get20RandomDutchUsers(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "RandomUserAPI.Get20RandomDutchUsers", params);
			java.util.List<randomuserapi.proxies.User> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<randomuserapi.proxies.User>();
				for (IMendixObject obj : objs)
					result.add(randomuserapi.proxies.User.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<randomuserapi.proxies.User> getRandomUserList(IContext context, java.lang.Long _nrOfRandomUsers)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NrOfRandomUsers", _nrOfRandomUsers);
			java.util.List<IMendixObject> objs = Core.execute(context, "RandomUserAPI.GetRandomUserList", params);
			java.util.List<randomuserapi.proxies.User> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<randomuserapi.proxies.User>();
				for (IMendixObject obj : objs)
					result.add(randomuserapi.proxies.User.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<randomuserapi.proxies.User> getRandomUserListByParameters(IContext context, java.lang.Long _nrOfRandomUsers, randomuserapi.proxies.Gender _gender, randomuserapi.proxies.Nationality _nationality)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NrOfRandomUsers", _nrOfRandomUsers);
			params.put("Gender", _gender == null ? null : _gender.name());
			params.put("Nationality", _nationality == null ? null : _nationality.name());
			java.util.List<IMendixObject> objs = Core.execute(context, "RandomUserAPI.GetRandomUserListByParameters", params);
			java.util.List<randomuserapi.proxies.User> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<randomuserapi.proxies.User>();
				for (IMendixObject obj : objs)
					result.add(randomuserapi.proxies.User.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}