// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package countriesv5.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import countriesv5.proxies.Countries;

public class StringToCountry extends CustomJavaAction<java.lang.String>
{
	private java.lang.String value;

	public StringToCountry(IContext context, java.lang.String value)
	{
		super(context);
		this.value = value;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(this.value == null || "".equals(this.value))
			return null;
			
		Countries country = parse(this.value);
		
		if(country == null) {
			for(Countries key : Countries.values()) {
				if(key.getCaption("en_US").equals(this.value)) {
					country = key;
					break;
				}
			}
		}
		
		if(country != null) {
			return country.toString();
		} else {
			Core.getLogger(this.toString()).warn("Invalid country: " + this.value);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringToCountry";
	}

	// BEGIN EXTRA CODE
	private Countries parse(String input) {
		try {
			return Countries.valueOf(input.replaceAll(" ", "_"));
		}
		catch (Exception e) {
			return null;
		}
	}
	// END EXTRA CODE
}
