// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package randomuserapi.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the RandomUserAPI module

	public static java.lang.String getRandomUserURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("RandomUserAPI.RandomUserURL");
	}
}