// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies;

public class Country
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CountriesV5.Country";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Alpha2Code("Alpha2Code"),
		Alpha3Code("Alpha3Code"),
		Capital("Capital"),
		Region("Region"),
		Subregion("Subregion"),
		Demonym("Demonym"),
		NativeName("NativeName"),
		NumericCode("NumericCode"),
		Flag("Flag"),
		Translations_JsonObject("CountriesV5.Translations_JsonObject"),
		CallingCodes_Country("CountriesV5.CallingCodes_Country"),
		Latlng_Country("CountriesV5.Latlng_Country");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Country(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CountriesV5.Country"));
	}

	protected Country(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countryMendixObject)
	{
		if (countryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CountriesV5.Country", countryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CountriesV5.Country");

		this.countryMendixObject = countryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Country.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static countriesv5.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return countriesv5.proxies.Country.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static countriesv5.proxies.Country initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new countriesv5.proxies.Country(context, mendixObject);
	}

	public static countriesv5.proxies.Country load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return countriesv5.proxies.Country.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Alpha2Code
	 */
	public final java.lang.String getAlpha2Code()
	{
		return getAlpha2Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha2Code
	 */
	public final java.lang.String getAlpha2Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha2Code.toString());
	}

	/**
	 * Set value of Alpha2Code
	 * @param alpha2code
	 */
	public final void setAlpha2Code(java.lang.String alpha2code)
	{
		setAlpha2Code(getContext(), alpha2code);
	}

	/**
	 * Set value of Alpha2Code
	 * @param context
	 * @param alpha2code
	 */
	public final void setAlpha2Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha2code)
	{
		getMendixObject().setValue(context, MemberNames.Alpha2Code.toString(), alpha2code);
	}

	/**
	 * @return value of Alpha3Code
	 */
	public final java.lang.String getAlpha3Code()
	{
		return getAlpha3Code(getContext());
	}

	/**
	 * @param context
	 * @return value of Alpha3Code
	 */
	public final java.lang.String getAlpha3Code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alpha3Code.toString());
	}

	/**
	 * Set value of Alpha3Code
	 * @param alpha3code
	 */
	public final void setAlpha3Code(java.lang.String alpha3code)
	{
		setAlpha3Code(getContext(), alpha3code);
	}

	/**
	 * Set value of Alpha3Code
	 * @param context
	 * @param alpha3code
	 */
	public final void setAlpha3Code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alpha3code)
	{
		getMendixObject().setValue(context, MemberNames.Alpha3Code.toString(), alpha3code);
	}

	/**
	 * @return value of Capital
	 */
	public final java.lang.String getCapital()
	{
		return getCapital(getContext());
	}

	/**
	 * @param context
	 * @return value of Capital
	 */
	public final java.lang.String getCapital(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Capital.toString());
	}

	/**
	 * Set value of Capital
	 * @param capital
	 */
	public final void setCapital(java.lang.String capital)
	{
		setCapital(getContext(), capital);
	}

	/**
	 * Set value of Capital
	 * @param context
	 * @param capital
	 */
	public final void setCapital(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String capital)
	{
		getMendixObject().setValue(context, MemberNames.Capital.toString(), capital);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of Subregion
	 */
	public final java.lang.String getSubregion()
	{
		return getSubregion(getContext());
	}

	/**
	 * @param context
	 * @return value of Subregion
	 */
	public final java.lang.String getSubregion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subregion.toString());
	}

	/**
	 * Set value of Subregion
	 * @param subregion
	 */
	public final void setSubregion(java.lang.String subregion)
	{
		setSubregion(getContext(), subregion);
	}

	/**
	 * Set value of Subregion
	 * @param context
	 * @param subregion
	 */
	public final void setSubregion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subregion)
	{
		getMendixObject().setValue(context, MemberNames.Subregion.toString(), subregion);
	}

	/**
	 * @return value of Demonym
	 */
	public final java.lang.String getDemonym()
	{
		return getDemonym(getContext());
	}

	/**
	 * @param context
	 * @return value of Demonym
	 */
	public final java.lang.String getDemonym(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Demonym.toString());
	}

	/**
	 * Set value of Demonym
	 * @param demonym
	 */
	public final void setDemonym(java.lang.String demonym)
	{
		setDemonym(getContext(), demonym);
	}

	/**
	 * Set value of Demonym
	 * @param context
	 * @param demonym
	 */
	public final void setDemonym(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String demonym)
	{
		getMendixObject().setValue(context, MemberNames.Demonym.toString(), demonym);
	}

	/**
	 * @return value of NativeName
	 */
	public final java.lang.String getNativeName()
	{
		return getNativeName(getContext());
	}

	/**
	 * @param context
	 * @return value of NativeName
	 */
	public final java.lang.String getNativeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NativeName.toString());
	}

	/**
	 * Set value of NativeName
	 * @param nativename
	 */
	public final void setNativeName(java.lang.String nativename)
	{
		setNativeName(getContext(), nativename);
	}

	/**
	 * Set value of NativeName
	 * @param context
	 * @param nativename
	 */
	public final void setNativeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nativename)
	{
		getMendixObject().setValue(context, MemberNames.NativeName.toString(), nativename);
	}

	/**
	 * @return value of NumericCode
	 */
	public final java.lang.String getNumericCode()
	{
		return getNumericCode(getContext());
	}

	/**
	 * @param context
	 * @return value of NumericCode
	 */
	public final java.lang.String getNumericCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NumericCode.toString());
	}

	/**
	 * Set value of NumericCode
	 * @param numericcode
	 */
	public final void setNumericCode(java.lang.String numericcode)
	{
		setNumericCode(getContext(), numericcode);
	}

	/**
	 * Set value of NumericCode
	 * @param context
	 * @param numericcode
	 */
	public final void setNumericCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numericcode)
	{
		getMendixObject().setValue(context, MemberNames.NumericCode.toString(), numericcode);
	}

	/**
	 * @return value of Flag
	 */
	public final java.lang.String getFlag()
	{
		return getFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of Flag
	 */
	public final java.lang.String getFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Flag.toString());
	}

	/**
	 * Set value of Flag
	 * @param flag
	 */
	public final void setFlag(java.lang.String flag)
	{
		setFlag(getContext(), flag);
	}

	/**
	 * Set value of Flag
	 * @param context
	 * @param flag
	 */
	public final void setFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String flag)
	{
		getMendixObject().setValue(context, MemberNames.Flag.toString(), flag);
	}

	/**
	 * @return value of Translations_JsonObject
	 */
	public final countriesv5.proxies.Translations getTranslations_JsonObject() throws com.mendix.core.CoreException
	{
		return getTranslations_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Translations_JsonObject
	 */
	public final countriesv5.proxies.Translations getTranslations_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		countriesv5.proxies.Translations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Translations_JsonObject.toString());
		if (identifier != null)
			result = countriesv5.proxies.Translations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Translations_JsonObject
	 * @param translations_jsonobject
	 */
	public final void setTranslations_JsonObject(countriesv5.proxies.Translations translations_jsonobject)
	{
		setTranslations_JsonObject(getContext(), translations_jsonobject);
	}

	/**
	 * Set value of Translations_JsonObject
	 * @param context
	 * @param translations_jsonobject
	 */
	public final void setTranslations_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.Translations translations_jsonobject)
	{
		if (translations_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Translations_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Translations_JsonObject.toString(), translations_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return value of CallingCodes_Country
	 */
	public final countriesv5.proxies.CallingCodes getCallingCodes_Country() throws com.mendix.core.CoreException
	{
		return getCallingCodes_Country(getContext());
	}

	/**
	 * @param context
	 * @return value of CallingCodes_Country
	 */
	public final countriesv5.proxies.CallingCodes getCallingCodes_Country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		countriesv5.proxies.CallingCodes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CallingCodes_Country.toString());
		if (identifier != null)
			result = countriesv5.proxies.CallingCodes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CallingCodes_Country
	 * @param callingcodes_country
	 */
	public final void setCallingCodes_Country(countriesv5.proxies.CallingCodes callingcodes_country)
	{
		setCallingCodes_Country(getContext(), callingcodes_country);
	}

	/**
	 * Set value of CallingCodes_Country
	 * @param context
	 * @param callingcodes_country
	 */
	public final void setCallingCodes_Country(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.CallingCodes callingcodes_country)
	{
		if (callingcodes_country == null)
			getMendixObject().setValue(context, MemberNames.CallingCodes_Country.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CallingCodes_Country.toString(), callingcodes_country.getMendixObject().getId());
	}

	/**
	 * @return value of Latlng_Country
	 */
	public final countriesv5.proxies.Latlng getLatlng_Country() throws com.mendix.core.CoreException
	{
		return getLatlng_Country(getContext());
	}

	/**
	 * @param context
	 * @return value of Latlng_Country
	 */
	public final countriesv5.proxies.Latlng getLatlng_Country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		countriesv5.proxies.Latlng result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Latlng_Country.toString());
		if (identifier != null)
			result = countriesv5.proxies.Latlng.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Latlng_Country
	 * @param latlng_country
	 */
	public final void setLatlng_Country(countriesv5.proxies.Latlng latlng_country)
	{
		setLatlng_Country(getContext(), latlng_country);
	}

	/**
	 * Set value of Latlng_Country
	 * @param context
	 * @param latlng_country
	 */
	public final void setLatlng_Country(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.Latlng latlng_country)
	{
		if (latlng_country == null)
			getMendixObject().setValue(context, MemberNames.Latlng_Country.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Latlng_Country.toString(), latlng_country.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final countriesv5.proxies.Country that = (countriesv5.proxies.Country) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CountriesV5.Country";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
