// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies;

public class Country_ISO3166_1
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject country_ISO3166_1MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CountriesV5.Country_ISO3166_1";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		NativeName("NativeName"),
		Letters_2("Letters_2"),
		Letters_3("Letters_3"),
		Number("Number"),
		NumberAsString("NumberAsString"),
		CountryEnumeration("CountryEnumeration"),
		Capital("Capital"),
		Demonym("Demonym"),
		TranslationDemonym("TranslationDemonym"),
		FlagURL("FlagURL"),
		Lattitude("Lattitude"),
		Longitude("Longitude"),
		CallingCode("CallingCode"),
		Region("Region"),
		Subregion("Subregion");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Country_ISO3166_1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CountriesV5.Country_ISO3166_1"));
	}

	protected Country_ISO3166_1(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject country_ISO3166_1MendixObject)
	{
		if (country_ISO3166_1MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CountriesV5.Country_ISO3166_1", country_ISO3166_1MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CountriesV5.Country_ISO3166_1");

		this.country_ISO3166_1MendixObject = country_ISO3166_1MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Country_ISO3166_1.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static countriesv5.proxies.Country_ISO3166_1 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return countriesv5.proxies.Country_ISO3166_1.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static countriesv5.proxies.Country_ISO3166_1 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new countriesv5.proxies.Country_ISO3166_1(context, mendixObject);
	}

	public static countriesv5.proxies.Country_ISO3166_1 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return countriesv5.proxies.Country_ISO3166_1.initialize(context, mendixObject);
	}

	public static java.util.List<countriesv5.proxies.Country_ISO3166_1> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<countriesv5.proxies.Country_ISO3166_1> result = new java.util.ArrayList<countriesv5.proxies.Country_ISO3166_1>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CountriesV5.Country_ISO3166_1" + xpathConstraint))
			result.add(countriesv5.proxies.Country_ISO3166_1.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of NativeName
	 */
	public final java.lang.String getNativeName()
	{
		return getNativeName(getContext());
	}

	/**
	 * @param context
	 * @return value of NativeName
	 */
	public final java.lang.String getNativeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NativeName.toString());
	}

	/**
	 * Set value of NativeName
	 * @param nativename
	 */
	public final void setNativeName(java.lang.String nativename)
	{
		setNativeName(getContext(), nativename);
	}

	/**
	 * Set value of NativeName
	 * @param context
	 * @param nativename
	 */
	public final void setNativeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nativename)
	{
		getMendixObject().setValue(context, MemberNames.NativeName.toString(), nativename);
	}

	/**
	 * @return value of Letters_2
	 */
	public final java.lang.String getLetters_2()
	{
		return getLetters_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Letters_2
	 */
	public final java.lang.String getLetters_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Letters_2.toString());
	}

	/**
	 * Set value of Letters_2
	 * @param letters_2
	 */
	public final void setLetters_2(java.lang.String letters_2)
	{
		setLetters_2(getContext(), letters_2);
	}

	/**
	 * Set value of Letters_2
	 * @param context
	 * @param letters_2
	 */
	public final void setLetters_2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String letters_2)
	{
		getMendixObject().setValue(context, MemberNames.Letters_2.toString(), letters_2);
	}

	/**
	 * @return value of Letters_3
	 */
	public final java.lang.String getLetters_3()
	{
		return getLetters_3(getContext());
	}

	/**
	 * @param context
	 * @return value of Letters_3
	 */
	public final java.lang.String getLetters_3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Letters_3.toString());
	}

	/**
	 * Set value of Letters_3
	 * @param letters_3
	 */
	public final void setLetters_3(java.lang.String letters_3)
	{
		setLetters_3(getContext(), letters_3);
	}

	/**
	 * Set value of Letters_3
	 * @param context
	 * @param letters_3
	 */
	public final void setLetters_3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String letters_3)
	{
		getMendixObject().setValue(context, MemberNames.Letters_3.toString(), letters_3);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of NumberAsString
	 */
	public final java.lang.String getNumberAsString()
	{
		return getNumberAsString(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberAsString
	 */
	public final java.lang.String getNumberAsString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NumberAsString.toString());
	}

	/**
	 * Set value of NumberAsString
	 * @param numberasstring
	 */
	public final void setNumberAsString(java.lang.String numberasstring)
	{
		setNumberAsString(getContext(), numberasstring);
	}

	/**
	 * Set value of NumberAsString
	 * @param context
	 * @param numberasstring
	 */
	public final void setNumberAsString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numberasstring)
	{
		getMendixObject().setValue(context, MemberNames.NumberAsString.toString(), numberasstring);
	}

	/**
	 * Set value of CountryEnumeration
	 * @param countryenumeration
	 */
	public final countriesv5.proxies.Countries getCountryEnumeration()
	{
		return getCountryEnumeration(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryEnumeration
	 */
	public final countriesv5.proxies.Countries getCountryEnumeration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CountryEnumeration.toString());
		if (obj == null)
			return null;

		return countriesv5.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CountryEnumeration
	 * @param countryenumeration
	 */
	public final void setCountryEnumeration(countriesv5.proxies.Countries countryenumeration)
	{
		setCountryEnumeration(getContext(), countryenumeration);
	}

	/**
	 * Set value of CountryEnumeration
	 * @param context
	 * @param countryenumeration
	 */
	public final void setCountryEnumeration(com.mendix.systemwideinterfaces.core.IContext context, countriesv5.proxies.Countries countryenumeration)
	{
		if (countryenumeration != null)
			getMendixObject().setValue(context, MemberNames.CountryEnumeration.toString(), countryenumeration.toString());
		else
			getMendixObject().setValue(context, MemberNames.CountryEnumeration.toString(), null);
	}

	/**
	 * @return value of Capital
	 */
	public final java.lang.String getCapital()
	{
		return getCapital(getContext());
	}

	/**
	 * @param context
	 * @return value of Capital
	 */
	public final java.lang.String getCapital(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Capital.toString());
	}

	/**
	 * Set value of Capital
	 * @param capital
	 */
	public final void setCapital(java.lang.String capital)
	{
		setCapital(getContext(), capital);
	}

	/**
	 * Set value of Capital
	 * @param context
	 * @param capital
	 */
	public final void setCapital(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String capital)
	{
		getMendixObject().setValue(context, MemberNames.Capital.toString(), capital);
	}

	/**
	 * @return value of Demonym
	 */
	public final java.lang.String getDemonym()
	{
		return getDemonym(getContext());
	}

	/**
	 * @param context
	 * @return value of Demonym
	 */
	public final java.lang.String getDemonym(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Demonym.toString());
	}

	/**
	 * Set value of Demonym
	 * @param demonym
	 */
	public final void setDemonym(java.lang.String demonym)
	{
		setDemonym(getContext(), demonym);
	}

	/**
	 * Set value of Demonym
	 * @param context
	 * @param demonym
	 */
	public final void setDemonym(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String demonym)
	{
		getMendixObject().setValue(context, MemberNames.Demonym.toString(), demonym);
	}

	/**
	 * @return value of TranslationDemonym
	 */
	public final java.lang.String getTranslationDemonym()
	{
		return getTranslationDemonym(getContext());
	}

	/**
	 * @param context
	 * @return value of TranslationDemonym
	 */
	public final java.lang.String getTranslationDemonym(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TranslationDemonym.toString());
	}

	/**
	 * Set value of TranslationDemonym
	 * @param translationdemonym
	 */
	public final void setTranslationDemonym(java.lang.String translationdemonym)
	{
		setTranslationDemonym(getContext(), translationdemonym);
	}

	/**
	 * Set value of TranslationDemonym
	 * @param context
	 * @param translationdemonym
	 */
	public final void setTranslationDemonym(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String translationdemonym)
	{
		getMendixObject().setValue(context, MemberNames.TranslationDemonym.toString(), translationdemonym);
	}

	/**
	 * @return value of FlagURL
	 */
	public final java.lang.String getFlagURL()
	{
		return getFlagURL(getContext());
	}

	/**
	 * @param context
	 * @return value of FlagURL
	 */
	public final java.lang.String getFlagURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FlagURL.toString());
	}

	/**
	 * Set value of FlagURL
	 * @param flagurl
	 */
	public final void setFlagURL(java.lang.String flagurl)
	{
		setFlagURL(getContext(), flagurl);
	}

	/**
	 * Set value of FlagURL
	 * @param context
	 * @param flagurl
	 */
	public final void setFlagURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String flagurl)
	{
		getMendixObject().setValue(context, MemberNames.FlagURL.toString(), flagurl);
	}

	/**
	 * @return value of Lattitude
	 */
	public final java.math.BigDecimal getLattitude()
	{
		return getLattitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Lattitude
	 */
	public final java.math.BigDecimal getLattitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lattitude.toString());
	}

	/**
	 * Set value of Lattitude
	 * @param lattitude
	 */
	public final void setLattitude(java.math.BigDecimal lattitude)
	{
		setLattitude(getContext(), lattitude);
	}

	/**
	 * Set value of Lattitude
	 * @param context
	 * @param lattitude
	 */
	public final void setLattitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lattitude)
	{
		getMendixObject().setValue(context, MemberNames.Lattitude.toString(), lattitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of CallingCode
	 */
	public final java.lang.String getCallingCode()
	{
		return getCallingCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CallingCode
	 */
	public final java.lang.String getCallingCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CallingCode.toString());
	}

	/**
	 * Set value of CallingCode
	 * @param callingcode
	 */
	public final void setCallingCode(java.lang.String callingcode)
	{
		setCallingCode(getContext(), callingcode);
	}

	/**
	 * Set value of CallingCode
	 * @param context
	 * @param callingcode
	 */
	public final void setCallingCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String callingcode)
	{
		getMendixObject().setValue(context, MemberNames.CallingCode.toString(), callingcode);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of Subregion
	 */
	public final java.lang.String getSubregion()
	{
		return getSubregion(getContext());
	}

	/**
	 * @param context
	 * @return value of Subregion
	 */
	public final java.lang.String getSubregion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subregion.toString());
	}

	/**
	 * Set value of Subregion
	 * @param subregion
	 */
	public final void setSubregion(java.lang.String subregion)
	{
		setSubregion(getContext(), subregion);
	}

	/**
	 * Set value of Subregion
	 * @param context
	 * @param subregion
	 */
	public final void setSubregion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subregion)
	{
		getMendixObject().setValue(context, MemberNames.Subregion.toString(), subregion);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return country_ISO3166_1MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final countriesv5.proxies.Country_ISO3166_1 that = (countriesv5.proxies.Country_ISO3166_1) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CountriesV5.Country_ISO3166_1";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
