// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package countriesv5.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the CountriesV5 module
	public static void country_ISO3166_1_DeleteTable(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "CountriesV5.Country_ISO3166_1_DeleteTable", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String countryToString(IContext context, countriesv5.proxies.Countries _country)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Country", _country == null ? null : _country.name());
			return (java.lang.String)Core.execute(context, "CountriesV5.CountryToString", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String demonym_Translation(IContext context, countriesv5.proxies.Country_ISO3166_1 _country)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Country", _country == null ? null : _country.getMendixObject());
			return (java.lang.String)Core.execute(context, "CountriesV5.Demonym_Translation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_GetCountries(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "CountriesV5.IVK_GetCountries", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static countriesv5.proxies.Country_ISO3166_1 sUB_Country_GetOrCreate(IContext context, countriesv5.proxies.Country _country)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Country", _country == null ? null : _country.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "CountriesV5.SUB_Country_GetOrCreate", params);
			return result == null ? null : countriesv5.proxies.Country_ISO3166_1.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_Country_SetGPS(IContext context, countriesv5.proxies.Country_ISO3166_1 _dBCountry, countriesv5.proxies.Country _country)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DBCountry", _dBCountry == null ? null : _dBCountry.getMendixObject());
			params.put("Country", _country == null ? null : _country.getMendixObject());
			Core.execute(context, "CountriesV5.SUB_Country_SetGPS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_Country_SetTranslations(IContext context, java.util.List<countriesv5.proxies.DemonymTranslations> _translationCommitList, java.lang.String _code, java.lang.String _translation, countriesv5.proxies.Country_ISO3166_1 _country)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_translationCommitList = null;
			if (_translationCommitList != null)
			{
				listparam_translationCommitList = new java.util.ArrayList<IMendixObject>();
				for (countriesv5.proxies.DemonymTranslations obj : _translationCommitList)
					listparam_translationCommitList.add(obj.getMendixObject());
			}
			params.put("TranslationCommitList", listparam_translationCommitList);
			params.put("Code", _code);
			params.put("Translation", _translation);
			params.put("Country", _country == null ? null : _country.getMendixObject());
			Core.execute(context, "CountriesV5.SUB_Country_SetTranslations", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static countriesv5.proxies.Countries sUB_CountryEnum_Get(IContext context, countriesv5.proxies.Country _country)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Country", _country == null ? null : _country.getMendixObject());
			java.lang.String result = (java.lang.String)Core.execute(context, "CountriesV5.SUB_CountryEnum_Get", params);
			if (result == null)
				return null;
			return countriesv5.proxies.Countries.valueOf(result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}